name: Release

on:
  push:
    branches: [main]
    paths:
      - ".changeset/**"
      - "packages/tw2panda/**"

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        working-directory: ./packages/tw2panda
        run: pnpm build

      - name: Test
        working-directory: ./packages/tw2panda
        run: pnpm test

      # - name: Release to dev tag
      #   if: steps.changesets.outputs.published != 'true'
      #   run: |
      #     git checkout main
      #     pnpm changeset version --snapshot dev
      #     pnpm changeset publish --tag dev
      #   env:
      #     NPM_TOKEN: ${{secrets.NPM_TOKEN}}
      #     NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      #     GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm changeset publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
